### ISSUE TITLE
Best case latency?

### ISSUE THREAD

**Issue by andybarry** [ai4ce/insta360_ros_driver#1]
Have you measured the best-case latency?  I'm curious what you are able to get, since I've really struggled with that on the Insta SDK.  A glass to glass measurement is usually what I use since it's pretty easy to do (point the camera at the screen with a stopwatch program running along with the camera output display, take a photo with a phone, compare the difference).

**Comment by simbaforrest** [comment]
@Abanesjo @Gaaaavin Any comments/suggestions?

**Comment by Gaaaavin** [comment]
@andybarry Thank you for your interest to the project.
Currently the best case latency we get is  ~187ms with raw image output and ~220ms with compressed image output. This is tested with a Insta360 X2 camera, with resolution and fps set to `1152_1152P30`, and with glass-to-glass measurement. Other resolution and fps setups usually lead to a latency >1s.
The annoying part with Insta360 SDK is that you don't always get the resolution and fps you specified, reference [here](https://github.com/Insta360Develop/CameraSDK-Cpp/issues/32#issuecomment-1546665287). The `1152_1152P30` setup actually give you a 2304x1152 resolution stream from both cameras. We are still testing with other available specifications with the X3 camera.
