### ISSUE TITLE
No device found

### ISSUE THREAD

**Issue by baptisteLynx** [ai4ce/insta360_ros_driver#4]
Hi ! 

First, thank you for providing this package ! 

I'm trying to use it with my One X2 but I'm facing some difficulties to detect the camera.
I connected the camera to my pc and configured the camera's USB mode to "Webcam". The udev configuration is up and I have the following return to ls -l : 
<img width="455" alt="ls-l" src="https://github.com/user-attachments/assets/5b7dd4f9-eb66-47a1-b834-9d0a0a7962d2">

Running the bringup lead me to this error : 
```
... logging to /home/baptiste/dev_ws/log/963d71e8-7728-11ef-99cb-f5d9d2c66137/roslaunch-baptiste-Asus-TUF-16594.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://localhost:46193/

SUMMARY
========

PARAMETERS
 * /D: [[0.0829955798117...
 * /K: [[305.85116609096...
 * /compressed_bag_folder: /home/bag/compressed
 * /raw_bag_folder: /home/bag/raw
 * /rosdistro: noetic
 * /rosversion: 1.16.0
 * /undistort: False
 * /undistorted_bag_folder: /home/bag/undisto...

NODES
  /
    bringup (insta360_ros_driver/insta360_ros_driver)
    live_processing (insta360_ros_driver/live_processing.py)
    rostopic_hz (insta360_ros_driver/rostopic_hz.sh)
    rqt_image_view (rqt_image_view/rqt_image_view)

ROS_MASTER_URI=http://localhost:11311

process[bringup-1]: started with pid [16608]
process[live_processing-2]: started with pid [16609]
process[rqt_image_view-3]: started with pid [16610]
process[rostopic_hz-4]: started with pid [16611]
[ERROR] [1726821305.111541144]: Opened Camera

no device found.
```
What am I doing wrong ? Is the camera configuration even correct ?  Feeling like a basic roocky mistake to me... 
Thank you for your help !

Best

**Comment by YogeshHCR** [comment]
Make sure the camera is in Android mode

> On the camera, swipe down the screen to the main menu, go to Settings->General, and set USB Mode to Android

**Comment by Gaaaavin** [comment]
@YogeshHCR Thank you for the answer!
