### ISSUE TITLE
Image is not as expected while running with X4

### ISSUE THREAD

**Issue by ajay-inkers** [ai4ce/insta360_ros_driver#7]
Hey guys,

I tried the driver with both X3 and X4 devices. The driver works pretty stable with X3. But when I tried with X4 I'm getting a corrupted image. I'm attaching the image for reference. Any input or idea to fix this issue will help a lot.
Thanks in advance.

![image](https://github.com/user-attachments/assets/cca17fb4-7618-434c-8a7f-68da79a8a0f2)

**Comment by ajay-inkers** [comment]
fixed

**Comment by nhat-m-le** [comment]
@ajay-inkers I am having the same issue. Could you let me know how to fix it? Thanks!

**Comment by webvenky** [comment]
@ajay-inkers  I'm having the same issue. Could you let me know how to fix this? Thank.
