### ISSUE TITLE
Where did camera intrinsics come from?

### ISSUE THREAD

**Issue by schmittlema** [ai4ce/insta360_ros_driver#8]
Hi,
Cool work, thanks for making this!

I was wondering where you get camera intrinsics from? I can image between different models they have different parameters, but I only see one set of parameters in config.yaml. Some clarity on this would be great, thanks!

**Comment by Gaaaavin** [comment]
We did an intrinsic calibration for the X2 camera with a checker board.
You may need to do the calibration by yourself if you are using a diffeerent caemra (X3, X4, etc.)
